#############################################################################################
# Arrbit Main Configuration
#############################################################################################

ENABLE_ARRBIT="false"             #Master ON/OFF switch

#############################################################################################
# PLUGIN SETTINGS
#############################################################################################

ENABLE_PLUGINS=" true"            #Master ON/OFF switch for plugins

INSTALL_PLUGIN_DEEZER="true"      # Install the Deezer (TrevTV) plugin
INSTALL_PLUGIN_TIDAL="true"       # Install the Tidal (TrevTV) plugin
INSTALL_PLUGIN_TUBIFARRY="true"   # Install the Tubifarry (TypNull) plugin 
##INSTALL_PLUGIN_DEEMIX="false"   # WIP not yet impleemented (ta264) plugin
##INSTALL_PLUGIN_QOBUZ="false"    # WIP not yet impleemented (TrevTV) plugin

ENBALE_PREMIUM="false"            #if you have premium accounts for Tidal,Deezer or Qobuz

PREMIUM_TIDAL="false"             #HQ releases (Lossless/24bit) and videos.
PREMIUM_DEEZER="false"            #HQ reeleases (lossless)
##PREMIUM_QOBUZ="false"           #WIP LOGIC not yet impleemented 

## Needed for autoconfig and videos services to run the best configurations.
## If you have no premium it is fine, video service will default to youtube as fallback and 
## only use usenet, torrents and soulseek for media search. 

#############################################################################################
#AUTOCONFIG 
#############################################################################################

ENABLE_AUTOCONFIG="true"           #Master ON/OFF switch for autoconfig service.

#############################################################################################
# AUTO-CONFIGURATION SETTINGS
#############################################################################################

CONFIGURE_MEDIA_MANAGEMENT="true"       # import extra files, file management , permissions.
CONFIGURE_METADATA_CONSUMER="false"     #
CONFIGURE_METADATA_WRITE="false"        #
CONFIGURE_METADATA_PLUGIN="false"       #
CONFIGURE_METADATA_PROFILES="false"     #  Profiles for edm,classical music, hip-hop, standard.
CONFIGURE_TRACK_NAMING="false"          #
CONFIGURE_UI_SETTINGS="false"           #
CONFIGURE_CUSTOM_SCRIPTS="false"        #
CONFIGURE_CUSTOM_FORMATS="false"        #
CONFIGURE_DELAY_PROFILES="false"        #
CONFIGURE_QUALITY_PROFILE="false"       #
CONFIGURE_QUALITY_DEFINITIONS="false"   #

#############################################################################################
# BEETS INTEGRATION
#############################################################################################

# If you use Beets for tagging/organizing, point to your config here:
# BEETS_CONFIG_PATH="/config/arrbit/beets-config.yaml"


################################################################################
# END OF CONFIGURATION
################################################################################
