################################################################################
# Arrbit Main Configuration
################################################################################

################################################################################
# COMMUNITY PLUGIN INSTALLATION SETTINGS
################################################################################

INSTALL_COMMUNITY_PLUGINS="true"

INSTALL_PLUGIN_DEEZER="true"
INSTALL_PLUGIN_TIDAL="true"
INSTALL_PLUGIN_TUBIFARRY="true"

################################################################################
# AUTO‑CONFIGURATION SETTINGS
################################################################################

INSTALL_AUTOCONFIG="false"

CONFIGURE_MEDIA_MANAGEMENT="false"
CONFIGURE_METADATA_CONSUMER="false"
CONFIGURE_METADATA_WRITE="false"
CONFIGURE_CUSTOM_SCRIPTS="false"
CONFIGURE_UI_SETTINGS="false"
CONFIGURE_METADATA_PROFILES="false"
CONFIGURE_TRACK_NAMING="false"
CONFIGURE_PLUGIN_METADATA="true"

################################################################################
# CUSTOM FORMATS SETTINGS
################################################################################

ENABLE_CUSTOM_FORMATS="true"
