################################################################################
# Arrbit Main Configuration
################################################################################

################################################################################
# PLUGIN SETTINGS
################################################################################

ENABLE_PLUGINS="false"

INSTALL_PLUGIN_DEEZER="true"    # Install the Deezer download plugin
INSTALL_PLUGIN_TIDAL="true"     # Install the Tidal download plugin
INSTALL_PLUGIN_TUBIFARRY="true" # Install the Tubifarry (TypNull) plugin

################################################################################
# AUTO-CONFIGURATION SETTINGS
################################################################################

ENABLE_AUTOCONFIG="false"

CONFIGURE_MEDIA_MANAGEMENT="false"
CONFIGURE_METADATA_CONSUMER="false"
CONFIGURE_METADATA_WRITE="false" 
CONFIGURE_METADATA_PLUGIN="false"
CONFIGURE_METADATA_PROFILES="false"
CONFIGURE_TRACK_NAMING="false"
CONFIGURE_UI_SETTINGS="false"
CONFIGURE_CUSTOM_SCRIPTS="false"
CONFIGURE_CUSTOM_FORMATS="false"
CONFIGURE_DELAY_PROFILES="false"
CONFIGURE_QUALITY_PROFILE="false"

################################################################################
# BEETS INTEGRATION
################################################################################

# If you use Beets for tagging/organizing, point to your config here:
# BEETS_CONFIG_PATH="/config/arrbit/beets-config.yaml"


################################################################################
# END OF CONFIGURATION
################################################################################
